// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4786.EverythingIsAwesome;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.CANTalon;
import java.util.Vector;

import org.usfirst.frc4786.EverythingIsAwesome.subsystems.*;
import org.usfirst.frc4786.EverythingIsAwesome.commands.*;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController frontRight;
    public static SpeedController frontLeft;
    public static SpeedController backRight;
    public static SpeedController backLeft;
    public static SpeedController rightArm;
    public static SpeedController leftArm;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	
         frontRight = new CANTalon(Subsystems.rioCheck.getPortNumber(1));
         frontLeft = new CANTalon(Subsystems.rioCheck.getPortNumber(14));
         backRight = new CANTalon(Subsystems.rioCheck.getPortNumber(0));
         backLeft = new CANTalon(Subsystems.rioCheck.getPortNumber(15));
         rightArm = new CANTalon(Subsystems.rioCheck.getPortNumber(2));
         leftArm = new CANTalon(Subsystems.rioCheck.getPortNumber(13));
    	
         
        
        /*
        SmartDashboard.putData("BackRight", new RightDrive());
        SmartDashboard.putData("BackLeft", new LeftDrive());
        SmartDashboard.putData("RightArmUp", new RightArmUp());
        SmartDashboard.putData("FrontRight", new LeftArmUp());
        SmartDashboard.putData("FrontRight", new RightArmDown());
        SmartDashboard.putData("FrontRight", new LeftArmDown());
        */
    	/*
        LiveWindow.addActuator("FrontRight", "Speed Controller 1", (Talon) frontRight);
        LiveWindow.addActuator("FrontLeft", "Speed Controller 2", (Talon) frontLeft);
        LiveWindow.addActuator("BackRight", "Speed Controller 3", (Talon) backRight);
        LiveWindow.addActuator("BackLeft", "Speed Controller 4", (Talon) backLeft);
        LiveWindow.addActuator("RightArm", "Speed Controller 5", (Talon) rightArm);
        LiveWindow.addActuator("LetfArm", "Speed Controller 6", (Talon) leftArm);
        */

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
